In [1]:
import pandas as pd
import numpy as np

In [15]:
# 创建一个 NumPy 数组，包含从0开始的数字
data = np.arange(12).reshape((4, 3))

# 使用 NumPy 数组创建 DataFrame
df = pd.DataFrame(data)

In [16]:
df

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [17]:
print(df)

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11


In [4]:
df.reshape(-1,1)

AttributeError: 'DataFrame' object has no attribute 'reshape'

In [18]:
df.values

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
raw=df.values
raw

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
raw_T=df.values.T
raw_T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [22]:
raw

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
raw.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
# raw 为 4行3列
# 改为 count 行，1列
# 即将 原始的 [4,3] -> 列向量
raw.reshape(-1,1)

array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [ 1],
       [ 4],
       [ 7],
       [10],
       [ 2],
       [ 5],
       [ 8],
       [11]])